# Generated by Django 2.1.11 on 2020-01-06 20:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('_uid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('clearbridge_appuser_id', models.IntegerField(unique=True)),
                ('user_selected_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=64, null=True)),
                ('gender', models.CharField(blank=True, max_length=64, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('eligible_for_rewards', models.BooleanField(default=True, help_text='Use this setting to tell the loyalty system to ignore this customer in future reward draws.')),
                ('subscription_token', models.CharField(db_index=True, editable=False, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.AlterIndexTogether(
            name='customer',
            index_together={('clearbridge_appuser_id', 'user_selected_level')},
        ),
    ]
