# Generated by Django 2.1.11 on 2020-01-06 20:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('alchemy_common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('_uid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('queryset', models.TextField()),
                ('sql_query', models.TextField()),
                ('model_name', models.CharField(max_length=128)),
                ('app_label', models.CharField(max_length=128)),
                ('field_name', models.CharField(max_length=128)),
                ('url', models.TextField()),
                ('filter_params', models.TextField()),
                ('is_initialized', models.BooleanField(default=False, help_text='True only if the initial customer ENTER/LEAVE events have been created in the DB for this segment.')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Segment',
                'verbose_name_plural': 'Segments',
                'ordering': ['created_at'],
            },
        ),
    ]
